image: node:18

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - yarn install
    - yarn lint:all
    - yarn build
  artifacts:
    expire_in: 1 hour
    paths:
      - dist
  only:
    - main
    - ci-cd-setup

deploy:
  stage: deploy
  needs:
    - build
  before_script:
    - apt-get update -qq && apt-get install -y -qq sshpass rsync
  script:
    - sshpass -V
    - export SSHPASS=$SSH_PASSWORD
    - sshpass -e rsync --progress --links --recursive --delete --checksum --exclude-from=./.sync-exclude -e "ssh -o StrictHostKeyChecking=no" $CI_PROJECT_DIR/dist/apps/restaurant-server/ $SSH_USER@$SERVER_IPADDRESS:$PROJECT_PATH
    - sshpass -e rsync --progress --links --recursive --delete --checksum --exclude-from=./.sync-exclude -e "ssh -o StrictHostKeyChecking=no" $CI_PROJECT_DIR/Dockerfile $CI_PROJECT_DIR/compose.yaml $SSH_USER@$SERVER_IPADDRESS:$PROJECT_PATH
    - sshpass -e ssh -o StrictHostKeyChecking=no $SSH_USER@$SERVER_IPADDRESS:$PROJECT_PATH "mkdir -p $PROJECT_PATH && cd $PROJECT_PATH && docker-compose up -d"
  only:
    - main
    - ci-cd-setup