image: node:18

stages:
  - install
  # - build
  - deploy

install:
  stage: install
  script:
    - yarn install
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

# build:
#   stage: build
#   script:
#     - npx nx build restaurant-server
#   artifacts:
#     expire_in: 1 hour
#     paths:
#       - dist
#   rules:
#     - if: '$CI_COMMIT_BRANCH == "main"'
#     - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

deploy:
  stage: deploy
  before_script:
    - apt-get update -qq && apt-get install -y -qq sshpass rsync
  script:
    - sshpass -V
    - export SSHPASS=$SSH_PASSWORD
    - sshpass -e "ssh -o StrictHostKeyChecking=no" $SSH_USER@$SERVER_IPADDRESS:$PROJECT_PATH "ls && cd vitaliikarietin-restaurantapi/ && git pull && docker-compose up"
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'