import { Template } from "../frontend/templates";
import { StoreProvider } from "../providers";
import "./global.css";

export const metadata = {
	title: "Welcome to restaurant-client",
	description: "Generated by create-nx-workspace"
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<body>
				<StoreProvider>
					<Template.MainLayout>
						{children}
					</Template.MainLayout>
				</StoreProvider>
			</body>
		</html>
	);
}
