// import { IntlProvider, FormattedMessage } from "react-intl";
// import { SnackbarProvider } from "notistack";
import { Template } from "../frontend/templates";
import { StoreProvider } from "../providers";

import "./global.css";

import messages_en from "../locales/en.json";

const messages = {
  en: messages_en,
};

const locale = "en";

export const metadata = {
	title: "Welcome to restaurant-client",
	description: "Generated by create-nx-workspace"
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<body>
				<StoreProvider>
					{/* <IntlProvider locale={locale} messages={messages[locale]}> */}
						{/* <SnackbarProvider> */}
							<Template.MainLayout>
								{children}
							</Template.MainLayout>
						{/* </SnackbarProvider> */}
					{/* </IntlProvider> */}
				</StoreProvider>
			</body>
		</html>
	);
}
